{{- if .Values.phpmyadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-mysql.fullname" . }}-phpmyadmin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress-mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.phpmyadmin.replicaCount }}
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: "{{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag }}"
          imagePullPolicy: {{ .Values.phpmyadmin.image.pullPolicy }}
          env:
            - name: PMA_HOST
              value: "{{ .Values.phpmyadmin.env.MYSQL_HOST }}"
            - name: PMA_PORT
              value: "{{ .Values.phpmyadmin.env.MYSQL_PORT }}"
            - name: PMA_ARBITRARY
              value: "1"  # Allows phpMyAdmin to connect to other databases as well
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pass
                  key: password
          ports:
            - containerPort: 80
              name: phpmyadmin
{{- end }}
